"""The claim-entailment battery — a saved, audited benchmark for grounding verifiers.

41 labeled (passage, claim) cases across 9 entailment failure modes (data/
claim_entailment_battery.json). Use it to evaluate any verifier that answers "does the passage
support the claim?"

Provenance (see the asset's `meta`): generated by 9 mode-specialist agents + a curator (54->41),
then validated by 5 independent blind stance-auditors on a SHUFFLED copy — 40/41 unanimous with
gold, 0 suspect, 1 stance_split (a synonym/notation-tolerance case). LLM-authored + LLM-audited;
not human ground truth.

    python -m litstream_evidence.claim_battery --verifier minicheck
"""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path

DATA = Path(__file__).resolve().parent / "data" / "claim_entailment_battery.json"


def load_battery(path: Path = DATA) -> list[dict]:
    """The list of labeled cases (each: passage, claim, gold, mode, rationale, audit)."""
    return json.loads(path.read_text())["cases"]


def battery_meta(path: Path = DATA) -> dict:
    return json.loads(path.read_text())["meta"]


def score(verifier, cases: list[dict] | None = None) -> dict:
    """Score a verifier (anything with `.verify(claim, passage) -> (bool, float)`) on the battery.
    Returns overall accuracy, per-mode breakdown, and the list of misses."""
    cases = cases or load_battery()
    by_mode: dict[str, list[int]] = defaultdict(lambda: [0, 0])
    misses: list[dict] = []
    correct = 0
    for c in cases:
        got = verifier.verify(c["claim"], c["passage"])[0]
        ok = (got == c["gold"])
        correct += ok
        by_mode[c["mode"]][0] += ok
        by_mode[c["mode"]][1] += 1
        if not ok:
            misses.append({"mode": c["mode"], "gold": c["gold"], "got": got, "claim": c["claim"]})
    return {"n": len(cases), "correct": correct, "accuracy": correct / len(cases),
            "by_mode": {m: {"correct": o, "n": n} for m, (o, n) in by_mode.items()},
            "misses": misses}


def main() -> None:
    ap = argparse.ArgumentParser(description="Score a verifier on the claim-entailment battery")
    ap.add_argument("--verifier", default="minicheck", choices=["overlap", "minicheck"])
    ap.add_argument("--minicheck-model", default="flan-t5-large")
    args = ap.parse_args()

    from litstream_evidence.ground_retrieval import make_verifier
    r = score(make_verifier(args.verifier, args.minicheck_model))
    print(f"\n{args.verifier}: {r['correct']}/{r['n']} = {r['accuracy']:.0%}")
    for m, d in sorted(r["by_mode"].items()):
        print(f"  {m:22} {d['correct']}/{d['n']}")
    print(f"misses ({len(r['misses'])}):")
    for x in r["misses"]:
        print(f"  [{x['mode']}] gold={x['gold']} got={x['got']} :: {x['claim'][:80]}")


if __name__ == "__main__":
    main()
